/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import model.ContactModel;
import swing.buttons.Button;

/**
 *
 * @author mateo
 */
public class ViewContactForm extends swing.panels.GradientPanel {

    /**
     * Creates new form ViewContactForm
     */
    public ViewContactForm() {
        initComponents();
    }
    
    public void loadData(ContactModel data){
        nombreLb.setText(data.getName());
        telefonoLb.setText(data.getPhone());
        carreraLb.setText(data.getDegree());
        universidadLb.setText(data.getUniversity());
    }

    public Button getAceptarBtn() {
        return aceptarBtn;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefonoLb = new javax.swing.JLabel();
        nombreLb = new javax.swing.JLabel();
        carreraLb = new javax.swing.JLabel();
        universidadLb = new javax.swing.JLabel();
        aceptarBtn = new swing.buttons.Button();

        setColor1(new java.awt.Color(255, 255, 255));
        setColor2(new java.awt.Color(255, 255, 255));
        setRound(20);

        telefonoLb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        telefonoLb.setForeground(new java.awt.Color(110, 112, 118));
        telefonoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefonoLb.setText("Telefono");

        nombreLb.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nombreLb.setForeground(new java.awt.Color(110, 112, 118));
        nombreLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLb.setText("Nombre");

        carreraLb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        carreraLb.setForeground(new java.awt.Color(110, 112, 118));
        carreraLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carreraLb.setText("Carrera");

        universidadLb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        universidadLb.setForeground(new java.awt.Color(110, 112, 118));
        universidadLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        universidadLb.setText("Universidad");

        aceptarBtn.setBackground(new java.awt.Color(109, 213, 237));
        aceptarBtn.setForeground(new java.awt.Color(255, 255, 255));
        aceptarBtn.setText("Aceptar");
        aceptarBtn.setBackgroundColor(new java.awt.Color(109, 213, 237));
        aceptarBtn.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        aceptarBtn.setHoverColor(new java.awt.Color(33, 147, 176));
        aceptarBtn.setRound(35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreLb, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(universidadLb, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                            .addComponent(carreraLb, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                            .addComponent(telefonoLb, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(nombreLb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(telefonoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(carreraLb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(universidadLb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.buttons.Button aceptarBtn;
    private javax.swing.JLabel carreraLb;
    private javax.swing.JLabel nombreLb;
    private javax.swing.JLabel telefonoLb;
    private javax.swing.JLabel universidadLb;
    // End of variables declaration//GEN-END:variables
}
