/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Point;
import javax.swing.JDialog;
import javax.swing.JFrame;
import swing.panels.GradientPanel;

/**
 *
 * @author mateo
 */
public class WindowTitleBar extends GradientPanel {

    /**
     * Creates new form WindowTitleBar
     */
    
    private JFrame jFrame;
    private JDialog jDialog;
    private Point initialClick;
    
    public WindowTitleBar() {
        initComponents();
        setColor1(Color.WHITE);
        setColor2(Color.WHITE);
        setRound(20);
        maximizeBtn.setVisible(false);
    }
    
     public void setJFrame(JFrame jFrame) {
        this.jFrame = jFrame;
        maximizeBtn.setVisible(true);
        
    }

    public void setJDialog(JDialog jDialog) {
        this.jDialog = jDialog;
        maximizeBtn.setVisible(false);
        
    }
    
    public void setTitleBarText(String text){
        titleTextLb.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new swing.buttons.Button();
        maximizeBtn = new swing.buttons.Button();
        jLabel1 = new javax.swing.JLabel();
        titleTextLb = new javax.swing.JLabel();
        maximizeBtn1 = new swing.buttons.Button();

        setColor1(new java.awt.Color(255, 255, 255));
        setColor2(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(109, 213, 237));
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-17.png"))); // NOI18N
        closeBtn.setBackgroundColor(new java.awt.Color(109, 213, 237));
        closeBtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        closeBtn.setHoverColor(new java.awt.Color(33, 147, 176));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        maximizeBtn.setBackground(new java.awt.Color(109, 213, 237));
        maximizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        maximizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-unchecked-checkbox-17.png"))); // NOI18N
        maximizeBtn.setBackgroundColor(new java.awt.Color(109, 213, 237));
        maximizeBtn.setEffectColor(new java.awt.Color(33, 147, 176));
        maximizeBtn.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        maximizeBtn.setHoverColor(new java.awt.Color(33, 147, 176));
        maximizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximizeBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 112, 118));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-contacts-17.png"))); // NOI18N
        jLabel1.setText("CRUD BASICO UTILZANDO H2");

        titleTextLb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        titleTextLb.setForeground(new java.awt.Color(110, 112, 118));
        titleTextLb.setText("Cargando..");

        maximizeBtn1.setBackground(new java.awt.Color(109, 213, 237));
        maximizeBtn1.setForeground(new java.awt.Color(255, 255, 255));
        maximizeBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-subtract-17.png"))); // NOI18N
        maximizeBtn1.setBackgroundColor(new java.awt.Color(109, 213, 237));
        maximizeBtn1.setEffectColor(new java.awt.Color(33, 147, 176));
        maximizeBtn1.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        maximizeBtn1.setHoverColor(new java.awt.Color(33, 147, 176));
        maximizeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximizeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(titleTextLb, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maximizeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(maximizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(maximizeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleTextLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maximizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int thisX = 0;
        int thisY = 0;

        if (jFrame != null) {
            thisX = jFrame.getLocation().x;
            thisY = jFrame.getLocation().y;
        } else {
            thisX = jDialog.getLocation().x;
            thisY = jDialog.getLocation().y;
        }

        // Determine how much the mouse moved since the initial click
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;

        if (jFrame != null) {
            jFrame.setLocation(X, Y);
        } else {
            jDialog.setLocation(X, Y);
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        initialClick = evt.getPoint();

    }//GEN-LAST:event_formMousePressed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed

        if (jFrame != null) {
            jFrame.dispose();
        }else {
            jDialog.dispose();
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void maximizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximizeBtnActionPerformed
        // TODO add your handling code here:
        if (jFrame != null) {
            if(jFrame.getExtendedState() == Frame.MAXIMIZED_BOTH){
                jFrame.setExtendedState(Frame.NORMAL);
            }else{
                jFrame.setExtendedState(Frame.MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_maximizeBtnActionPerformed

    private void maximizeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximizeBtn1ActionPerformed
        // TODO add your handling code here:
        if(jFrame != null){
            jFrame.setExtendedState(Frame.ICONIFIED);
        }
    }//GEN-LAST:event_maximizeBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.buttons.Button closeBtn;
    private javax.swing.JLabel jLabel1;
    private swing.buttons.Button maximizeBtn;
    private swing.buttons.Button maximizeBtn1;
    private javax.swing.JLabel titleTextLb;
    // End of variables declaration//GEN-END:variables
}
